//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string NameProdact { get; set; }
        public Nullable<int> TypeProductId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string DescriptionProduct { get; set; }
        public Nullable<int> Yearsofwarranty { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> salePrice { get; set; }
        public Nullable<System.DateTime> OperatingDate { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
